name: IP Blacklist

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
   
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Fetch
      run: | 
        curl -G https://api.abuseipdb.com/api/v2/blacklist -d confidenceMinimum=100 -d limit=9999999 -d plaintext -H "Key: ${{ secrets.ABUSEIPDB_TOKEN }}" -H "Accept: text/plain" > abuseipdb_blacklist_ip_score_100.txt || true
        curl -G https://api.abuseipdb.com/api/v2/blacklist -d confidenceMinimum=75 -d limit=9999999 -d plaintext -H "Key: ${{ secrets.ABUSEIPDB_TOKEN }}" -H "Accept: text/plain" > abuseipdb_blacklist_ip_score_75.txt || true
        curl http://antivirus.neu.edu.cn/ssh/lists/neu.txt -H "Accept: text/plain" > neucert_blacklist_ip.txt || true
        curl https://blackip.ustc.edu.cn/list.php?txt -H "Accept: text/plain" > ustc_blacklist_ip.txt || true
        for F in `ls *.txt`;do echo "">> $F; done
        cat *.txt|grep -v "#"|grep -v "127.0.0.1"|sort|uniq > all_blacklist.txt
    - name: Commit
      run: |
        git config --global user.email action@github.com
        git config --global user.name Action
        git add .
        git commit -m "Update IP." -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main 
